### ISSUE TITLE
License of CSS, JavaScript and images - COPIED TO REPO

### ISSUE THREAD

**Issue by Calinou** [css-javascript-toolbox/css-javascript-toolbox-plugin#19]
COPIED TO REPO: https://github.com/wipeoutmedia/css-javascript-toolbox-plus/issues/61

It appears the CSS/JavaScript/images of this plugin is under a proprietary license, according to `css-js-toolbox.php`:

```
License:

The Software is package as a WordPress¨ plugin.  The PHP code associated with the Software is licensed under the GPL version 2.0 license (as found at http://www.gnu.org/licenses/gpl-2.0.txt GNU/GPLv2 or "GPLv2"). You may redistribute, repackage, and modify the PHP code as you see fit and as consistent with GPLv2.

The remaining portions of the Software ("Proprietary Portion"), which includes all images, cascading style sheets, and JavaScript are NOT licensed under GPLv2 and are considered proprietary to Licensor and are solely licensed under the remaining terms of this Agreement.  The Proprietary Portion may not be redistributed, repackaged, or otherwise modified.
```

Would you please reconsider relicensing those parts (of the free version distributed on WordPress.org) under GPL or compatible license? This plugin looks powerful, but I'd like to use exclusively free as in freedom plugins on my sites -- not to mention WordPress.org doesn't normally allow proprietary CSS/JS/images.

For images (where GPL is not suitable), you can use [CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by pizzamaker** [comment]
Agreed, it would be very positive to have it freely licensed.
